# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
permalink: /:year/:month/:day/:title 
# Site settings
title: Takanori HARA
author:
  name: Takanori HARA
  email: hara.takanori.hm8 [at] is.naist.jp
  github: oakeshott
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oakeshott.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# highlighter: pygments
redcarpet:
  extensions: [
    "no_intra_emphasis",
    "fenced_code_blocks",
    "autolink",
    "tables",
    "footnotes",
    "strikethrough",
    "lax_html_blocks",
    "superscript"
    ]
exclude: ["gulpfile.js", "bower.json", "sync.sh", "Gemfile", "Gemfile.lock"]
