baseURL = "https://oakeshott.github.io/"
languageCode = "ja"
DefaultContentLanguage = "ja"
title = "Takanori Hara"
theme = "researcher"
canonifyurls = true

googleAnalytics = "UA-106011657-1"
[params]
  author = "Takanori HARA"
  description = ""
  customCSS = ["/custom.css"]
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Helvetica"
    pageWidth = "750px"
    avatarSize = "120px"
    colorBlack = "#494949"
    colorRed = "#889955"
  [params.footer]
    text = "Takanori Hara"

[menus]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Publication"
    url = "/#publication"
    weight = 1
  [[menu.main]]
    name = "About (JPN)"
    url = "/about"
    weight = 2
